on:
  pull_request:
  push:
    branches: [develop]

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: files
        uses: jitterbit/get-changed-files@v1
      - name: Check if dockerfiles/* changed
        run: |
          for file in ${{ steps.files.output.modified }}; do
            if [[ $file == "dockerfiles/"* ]]; then
              echo "$file changed"
              echo "::set-output name=changed::true"
            fi
          done
      - name: Push docker image
        if: steps.docker-check.outputs.changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        uses: docker/setup-buildx-action@v2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ayd_backend:latest
  code-cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@v1.0.0
      if: always()
